# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CICD

on:
  push:
    branches: ["master"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_MAIN_SERVER=${{secrets.REACT_APP_MAIN_SERVER}}" >> .env
          echo "REACT_APP_SOCKET_SERVER=${{secrets.REACT_APP_SOCKET_SERVER}}" >> .env
          echo "REACT_APP_OAUTH2_LOGIN=${{secrets.REACT_APP_OAUTH2_LOGIN}}" >> .env
          echo "REACT_APP_OAUTH2_LOGOUT=${{secrets.REACT_APP_OAUTH2_LOGOUT}}" >> .env
          cat .env

      - name: Install dependencies
        run: npm install

      - name: Build static file
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://word-storage
